# -*- coding: utf-8 -*-
"""Copy of Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vwKZf6P4A3oJMBZO5HkKOtQhz3Jh3rpj
"""

!pip install opencv-python

from google.colab import files
# The file '/content/rajiai.jpg' already exists in the Colab environment.
# The 'files.upload()' function is typically used to upload files from your local machine.
# You can directly use the path '/content/rajiai.jpg' with functions like cv2.imread()
# if you intend to load the image for processing.

!pip install mediapipe

import cv2
import matplotlib.pyplot as plt

# Load the image (replace with your uploaded file name)
img = cv2.imread('raj.jpeg')

# Convert to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Load Haar Cascade model
face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
)

# Detect faces
faces = face_cascade.detectMultiScale(gray, 1.3, 5)

# Draw rectangles around faces
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)

# Convert BGR to RGB for display
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Show image
plt.imshow(img_rgb)
plt.axis('off')
plt.show()